// src/App.tsx
import { useCallback, useEffect, useState } from 'react';
import { createVault, unlockVault, WrongPassphraseError } from './crypto';
import { loadHeader, saveHeader } from './lib/db';
import { Messenger } from './Messenger';
import { ReloadPrompt } from './ReloadPrompt';

// Auto-lock after this much inactivity — the DEK is dropped from memory.
const IDLE_LOCK_MS = 5 * 60 * 1000;

type Phase = 'loading' | 'create' | 'unlock' | 'open';
type StatusKind = '' | 'ok' | 'err';

export function App() {
  const [phase, setPhase] = useState<Phase>('loading');
  const [passphrase, setPassphrase] = useState('');
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState('');
  const [statusKind, setStatusKind] = useState<StatusKind>('');
  const [dek, setDek] = useState<CryptoKey | null>(null);

  useEffect(() => {
    void loadHeader().then((header) => setPhase(header ? 'unlock' : 'create'));
  }, []);

  function say(msg: string, kind: StatusKind = '') {
    setStatus(msg);
    setStatusKind(kind);
  }

  async function onCreate() {
    if (passphrase.length < 8) return say('Mindestens 8 Zeichen.', 'err');
    setBusy(true);
    say('Leite Schlüssel ab (Argon2id, 256 MiB)…');
    try {
      const { header, dek: newDek } = await createVault(passphrase);
      await saveHeader(header);
      setDek(newDek);
      setPassphrase('');
      setPhase('open');
      say('');
    } catch (e) {
      say('Fehler: ' + (e as Error).message, 'err');
    } finally {
      setBusy(false);
    }
  }

  async function onUnlock() {
    setBusy(true);
    say('Entsperre (Argon2id)…');
    try {
      const header = await loadHeader();
      if (!header) throw new Error('Kein Tresor gefunden.');
      const newDek = await unlockVault(passphrase, header);
      setDek(newDek);
      setPassphrase('');
      setPhase('open');
      say('');
    } catch (e) {
      if (e instanceof WrongPassphraseError) say('Falsche Passphrase.', 'err');
      else say('Fehler: ' + (e as Error).message, 'err');
    } finally {
      setBusy(false);
    }
  }

  const lock = useCallback(() => {
    setDek(null);
    setPhase('unlock');
    say('Gesperrt. DEK aus dem RAM entfernt.');
  }, []);

  // Auto-lock on inactivity while unlocked.
  useEffect(() => {
    if (phase !== 'open') return;
    let timer = window.setTimeout(lock, IDLE_LOCK_MS);
    const reset = () => {
      clearTimeout(timer);
      timer = window.setTimeout(lock, IDLE_LOCK_MS);
    };
    const events: (keyof WindowEventMap)[] = ['pointerdown', 'keydown', 'touchstart'];
    for (const e of events) window.addEventListener(e, reset, { passive: true });
    return () => {
      clearTimeout(timer);
      for (const e of events) window.removeEventListener(e, reset);
    };
  }, [phase, lock]);

  if (phase === 'open' && dek) {
    return (
      <>
        <Messenger dek={dek} onLock={lock} />
        <ReloadPrompt />
      </>
    );
  }

  return (
    <>
      <h1>SCYTALE</h1>
      <p className="sub">Ende-zu-Ende verschlüsselt · Client-Side</p>

      {phase === 'loading' && <div className="panel">Lade Tresor…</div>}

      {phase === 'create' && (
        <div className="panel">
          <label htmlFor="pp">Neue Passphrase (min. 8 Zeichen)</label>
          <input
            id="pp"
            type="password"
            value={passphrase}
            autoComplete="new-password"
            onChange={(e) => setPassphrase(e.target.value)}
          />
          <button onClick={onCreate} disabled={busy}>
            Tresor erstellen
          </button>
          <div className={`status ${statusKind}`}>{status}</div>
        </div>
      )}

      {phase === 'unlock' && (
        <div className="panel">
          <label htmlFor="pp">Passphrase</label>
          <input
            id="pp"
            type="password"
            value={passphrase}
            autoComplete="current-password"
            onChange={(e) => setPassphrase(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && onUnlock()}
          />
          <button onClick={onUnlock} disabled={busy}>
            Entsperren
          </button>
          <div className={`status ${statusKind}`}>{status}</div>
        </div>
      )}
      <ReloadPrompt />
    </>
  );
}

// src/App.svelte
<script lang="ts">
  import { createVault, unlockVault, WrongPassphraseError } from './crypto';
  import { loadHeader, saveHeader } from './lib/db';
  import Messenger from './Messenger.svelte';

  type Phase = 'loading' | 'create' | 'unlock' | 'open';

  let phase = $state<Phase>('loading');
  let passphrase = $state('');
  let busy = $state(false);
  let status = $state('');
  let statusKind = $state<'' | 'ok' | 'err'>('');
  let dek = $state<CryptoKey | null>(null);

  (async () => {
    const header = await loadHeader();
    phase = header ? 'unlock' : 'create';
  })();

  function setStatus(msg: string, kind: '' | 'ok' | 'err' = '') {
    status = msg;
    statusKind = kind;
  }

  async function onCreate() {
    if (passphrase.length < 8) return setStatus('Mindestens 8 Zeichen.', 'err');
    busy = true;
    setStatus('Leite Schlüssel ab (Argon2id, 256 MiB)…');
    try {
      const { header, dek: newDek } = await createVault(passphrase);
      await saveHeader(header);
      dek = newDek;
      passphrase = '';
      phase = 'open';
      setStatus('');
    } catch (e) {
      setStatus('Fehler: ' + (e as Error).message, 'err');
    } finally {
      busy = false;
    }
  }

  async function onUnlock() {
    busy = true;
    setStatus('Entsperre (Argon2id)…');
    try {
      const header = await loadHeader();
      if (!header) throw new Error('Kein Tresor gefunden.');
      dek = await unlockVault(passphrase, header);
      passphrase = '';
      phase = 'open';
      setStatus('');
    } catch (e) {
      if (e instanceof WrongPassphraseError) setStatus('Falsche Passphrase.', 'err');
      else setStatus('Fehler: ' + (e as Error).message, 'err');
    } finally {
      busy = false;
    }
  }

  function lock() {
    dek = null;
    phase = 'unlock';
    setStatus('Gesperrt. DEK aus dem RAM entfernt.');
  }
</script>

{#if phase === 'open' && dek}
  <Messenger {dek} onLock={lock} />
{:else}
  <h1>SCYTALE</h1>
  <p class="sub">Ende-zu-Ende verschlüsselt · Client-Side</p>

  {#if phase === 'loading'}
    <div class="panel">Lade Tresor…</div>
  {:else if phase === 'create'}
    <div class="panel">
      <label for="pp">Neue Passphrase (min. 8 Zeichen)</label>
      <input id="pp" type="password" bind:value={passphrase} autocomplete="new-password" />
      <button onclick={onCreate} disabled={busy}>Tresor erstellen</button>
      <div class="status {statusKind}">{status}</div>
    </div>
  {:else if phase === 'unlock'}
    <div class="panel">
      <label for="pp">Passphrase</label>
      <input
        id="pp"
        type="password"
        bind:value={passphrase}
        autocomplete="current-password"
        onkeydown={(e) => e.key === 'Enter' && onUnlock()}
      />
      <button onclick={onUnlock} disabled={busy}>Entsperren</button>
      <div class="status {statusKind}">{status}</div>
    </div>
  {/if}
{/if}
